version: '3.9'
services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    networks:
      - movies-network

  auth_api:
    build: .
    container_name: auth_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres_db
    networks:
      - movies-network

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_auth_db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - movies-network

networks:
  movies-network:
    name: movies-network
