version: '3.9'
services:
  redis_auth:
    image: redis:6.2.6-alpine
    container_name: redis_auth
    ports:
      - "6379:6379"
    networks:
      - movies-network

#  auth_api:
#    build: .
#    container_name: auth_api
#    ports:
#      - "5000:5000"
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - postgres_db
#    networks:
#      - movies-network

  postgres_auth:
    image: postgres:13
    container_name: postgres_auth
#    volumes:
#      - postgres_auth:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - movies-network


#volumes:
#  postgres_auth:

networks:
  movies-network:
    name: movies-network
