version: '3.9'
services:
  redis_auth:
    image: redis:6.2.6-alpine
    container_name: redis_auth
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - auth-network

  postgres_auth:
    image: postgres:13
    container_name: postgres_auth
    restart: always
    volumes:
      - postgres_auth:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - auth-network

  auth_api:
    build: .
    container_name: auth_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres_auth
      - REDIS_HOST=redis_auth
    depends_on:
      - redis_auth
      - postgres_auth
    networks:
      - auth-network

  testing_redis_auth:
    image: redis:6.2.6-alpine
    container_name: testing_redis_auth
    restart: always
    ports:
      - "127.0.0.1:${TEST_REDIS_PORT}:${TEST_REDIS_PORT}"
    networks:
      - auth-network

  testing_postgres_auth:
    image: postgres:13
    container_name: testing_postgres_auth
    restart: always
    volumes:
      - postgres_auth:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=auth_test
      - POSTGRES_USER=auth_test
      - POSTGRES_PASSWORD=auth_test
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=65432
    ports:
      - "127.0.0.1:${TEST_DB_PORT}:5432"
    networks:
      - auth-network


volumes:
  postgres_auth:

networks:
  auth-network:
    name: auth-network
